//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InspectionSystemManager {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LanguageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguageResource() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InspectionSystemManager.LanguageResource", typeof(LanguageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Algorithm Area과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AlgorithmArea {
            get {
                return ResourceManager.GetString("AlgorithmArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Algorithm
        ///Copy과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AlgorithmCopy {
            get {
                return ResourceManager.GetString("AlgorithmCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Algorithm
        ///-과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AlgorithmMinus {
            get {
                return ResourceManager.GetString("AlgorithmMinus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Algorithm
        ///+과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AlgorithmPlus {
            get {
                return ResourceManager.GetString("AlgorithmPlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Algorithm
        ///Set과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AlgorithmSet {
            get {
                return ResourceManager.GetString("AlgorithmSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Apply
        ///Map Data과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ApplyMapData {
            get {
                return ResourceManager.GetString("ApplyMapData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Inspection and Algorithm Area Setting Window과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AreaSettingWindowTitle {
            get {
                return ResourceManager.GetString("AreaSettingWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Confirm과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Inspection Area과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string InspectionArea {
            get {
                return ResourceManager.GetString("InspectionArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Inspection
        ///Area Copy과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string InspectionAreaCopy {
            get {
                return ResourceManager.GetString("InspectionAreaCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Inspection
        ///Area -과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string InspectionAreaMinus {
            get {
                return ResourceManager.GetString("InspectionAreaMinus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Inspection
        ///Area +과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string InspectionAreaPlus {
            get {
                return ResourceManager.GetString("InspectionAreaPlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Inspection Area Set과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string InspectionAreaSet {
            get {
                return ResourceManager.GetString("InspectionAreaSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set
        ///Map Data과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SetMapData {
            get {
                return ResourceManager.GetString("SetMapData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show All Area과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ShowAllArea {
            get {
                return ResourceManager.GetString("ShowAllArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Teaching Window과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TeachingWindow {
            get {
                return ResourceManager.GetString("TeachingWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Inspection Window과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TitleName {
            get {
                return ResourceManager.GetString("TitleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Camera Live과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ToolTip_CameraLive {
            get {
                return ResourceManager.GetString("ToolTip_CameraLive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cross Bar과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ToolTip_CrossBar {
            get {
                return ResourceManager.GetString("ToolTip_CrossBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Image Auto Save과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ToolTip_ImageAutoSave {
            get {
                return ResourceManager.GetString("ToolTip_ImageAutoSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Image Configuration Save과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ToolTip_ImageConfigurationSave {
            get {
                return ResourceManager.GetString("ToolTip_ImageConfigurationSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Image Load과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ToolTip_ImageLoad {
            get {
                return ResourceManager.GetString("ToolTip_ImageLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Image Save과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ToolTip_ImageSave {
            get {
                return ResourceManager.GetString("ToolTip_ImageSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Inspection과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ToolTip_Inspection {
            get {
                return ResourceManager.GetString("ToolTip_Inspection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   One Shot Inspection과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ToolTip_OneShotInspection {
            get {
                return ResourceManager.GetString("ToolTip_OneShotInspection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Result Display과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ToolTip_ResultDisplay {
            get {
                return ResourceManager.GetString("ToolTip_ResultDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set Image Auto Delete과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ToolTip_SetImageAutoDelete {
            get {
                return ResourceManager.GetString("ToolTip_SetImageAutoDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Teaching과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ToolTip_Teaching {
            get {
                return ResourceManager.GetString("ToolTip_Teaching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Teaching Save과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ToolTip_TeachingSave {
            get {
                return ResourceManager.GetString("ToolTip_TeachingSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vision과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Vision {
            get {
                return ResourceManager.GetString("Vision", resourceCulture);
            }
        }
    }
}
