//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPVisionInspectionFramework {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LanguageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguageResource() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KPVisionInspectionFramework.LanguageResource", typeof(LanguageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Align과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Align {
            get {
                return ResourceManager.GetString("Align", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Auto과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Auto {
            get {
                return ResourceManager.GetString("Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Calibration과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Calibration {
            get {
                return ResourceManager.GetString("Calibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Config과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Config {
            get {
                return ResourceManager.GetString("Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Data과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///    DIO과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DIO {
            get {
                return ResourceManager.GetString("DIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Ethernet과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Ethernet {
            get {
                return ResourceManager.GetString("Ethernet", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Exit과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Folder과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Folder {
            get {
                return ResourceManager.GetString("Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Good과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Good {
            get {
                return ResourceManager.GetString("Good", resourceCulture);
            }
        }
        
        /// <summary>
        ///    History과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Inspection Main과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string InspectionMain {
            get {
                return ResourceManager.GetString("InspectionMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Inspection Operating과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string InspectionOperating {
            get {
                return ResourceManager.GetString("InspectionOperating", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Light과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Log과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Log {
            get {
                return ResourceManager.GetString("Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///    MapData과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MapData {
            get {
                return ResourceManager.GetString("MapData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NG과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NG {
            get {
                return ResourceManager.GetString("NG", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Recipe과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Recipe {
            get {
                return ResourceManager.GetString("Recipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Result과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Comment과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ResultComment {
            get {
                return ResourceManager.GetString("ResultComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Result과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ResultTitle {
            get {
                return ResourceManager.GetString("ResultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Result Window과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ResultWindow {
            get {
                return ResourceManager.GetString("ResultWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Save과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Serial과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Serial {
            get {
                return ResourceManager.GetString("Serial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Setting과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Status과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Stop과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string System {
            get {
                return ResourceManager.GetString("System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Total과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vision과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Vision {
            get {
                return ResourceManager.GetString("Vision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yield과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Yield {
            get {
                return ResourceManager.GetString("Yield", resourceCulture);
            }
        }
    }
}
